name: meal_picker
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.17.0 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.3
  google_fonts: 3.0.0
  hive: 2.2.1
  hive_flutter: 1.1.0
  uuid: 3.0.6
  path_provider: 2.0.10
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: ^2.0.0
  lints: 2.0.0
  build_runner: 2.1.11
  hive_generator: 1.1.3
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true

